language: node_js
node_js:
  - "6"
sudo: false
env:
  global:
    - REGION=us
    - APP_ID=WI5a89CtPIOrWpvIwzNfOg9R-MdYXbMMI
    - APP_KEY=RUoMOSD8RNlpd0MIIiSDi7BU
install:
  - npm install
  - typings install
script:
  - npm test
notifications:
  webhooks: https://hook.bearychat.com/=bw52Y/travis/82822d77481fb732997758d83dbedfec